"""NCAA football team normalization (FBS + common Odds API / cfbfastR names)."""

from __future__ import annotations

import re
from typing import Iterable

# Common mascots stripped so "Alabama Crimson Tide" → "ALABAMA"
_MASCOTS = {
    "CRIMSON TIDE",
    "BULLDOGS",
    "TIGERS",
    "WILDCATS",
    "BEARS",
    "EAGLES",
    "HAWKS",
    "LIONS",
    "PANTHERS",
    "COUGARS",
    "HUSKIES",
    "SPARTANS",
    "WOLVERINES",
    "BUCKEYES",
    "SOONERS",
    "LONGHORNS",
    "NITTANY LIONS",
    "FIGHTING IRISH",
    "TROJANS",
    "BRUINS",
    "DUCKS",
    "BEAVERS",
    "HURRICANES",
    "SEMINOLES",
    "GATORS",
    "VOLUNTEERS",
    "COMMODORES",
    "GAMECOCKS",
    "TAR HEELS",
    "BLUE DEVILS",
    "ORANGE",
    "HOOSIERS",
    "BOILERMAKERS",
    "BADGERS",
    "HAWKEYES",
    "GOLDEN GOPHERS",
    "CORNHUSKERS",
    "TERRAPINS",
    "SCARLET KNIGHTS",
    "MOUNTAINEERS",
    "RAZORBACKS",
    "AGGIES",
    "REBELS",
    "GREEN WAVE",
    "MEAN GREEN",
    "HORNED FROGS",
    "MUSTANGS",
    "BEARCATS",
    "BEAR CATS",
    "CARDINALS",
    "SUN DEVILS",
    "UTES",
    "BUFFALOES",
    "COWBOYS",
    "CYCLONES",
    "JAYHAWKS",
    "RED RAIDERS",
    "HOOSIERS",
    "BOILERMAKERS",
    "FIGHTING ILLINI",
    "WILDCATS",
    "HOKIES",
    "CAVALIERS",
    "YELLOW JACKETS",
    "DEMON DEACONS",
    "WOLFPACK",
    "BLUE RAIDERS",
    "THUNDERING HERD",
    "GOLDEN EAGLES",
    "ROCKETS",
    "FALCONS",
    "BOBCATS",
    "CHIPPEWAS",
    "BRONCOS",
    "ROCKY MOUNTAIN",
    "RAINBOW WARRIORS",
    "WARRIORS",
    "HORNETS",
    "BISON",
    "GAMECOCKS",
    "AZTECS",
    "WOLFPACK",
    "FROGS",
    "SOONERS",
    # Group of 5 / FBS mascots (needed so Action Network rows match the odds feed)
    "ZIPS",
    "REDHAWKS",
    "RED HAWKS",
    "GOLDEN HURRICANE",
    "GOLDEN FLASHES",
    "ROADRUNNERS",
    "OWLS",
    "PIRATES",
    "VANDALS",
    "BLUE HENS",
    "CHANTICLEERS",
    "RED WOLVES",
    "MONARCHS",
    "HILLTOPPERS",
    "JAGUARS",
    "RAGIN CAJUNS",
    "RAGIN' CAJUNS",
    "WARHAWKS",
    "WOLF PACK",
    "LOBOS",
    "BULLS",
    "PANTHERS",
    "MINERS",
    "MIDSHIPMEN",
    "KNIGHTS",
    "COLONELS",
    "SEAHAWKS",
    "TRITONS",
    "ANTEATERS",
    "MATADORS",
    "TITANS",
    "GAUCHOS",
    "49ERS",
    # FCS mascots (early-season buy games appear on the board)
    "BLACK BEARS",
    "GOLDEN LIONS",
    "DELTA DEVILS",
    "SYCAMORES",
    "BEARKATS",
    "JACKRABBITS",
    "PENGUINS",
    "GOVERNORS",
    "RACERS",
    "DEMONS",
    "LUMBERJACKS",
    "VIKINGS",
    "BUCCANEERS",
    "DUKES",
    "LAKERS",
    "TEXANS",
    "TRAILBLAZERS",
    "VAQUEROS",
    "BENGALS",
    "BRAVES",
    "WOLVES",
    "RAMS",
    "LEOPARDS",
    "CRUSADERS",
    "TOMMIES",
    "BULLDOGS",
    "PALADINS",
    "CATAMOUNTS",
    "PHOENIX",
    "TERRIERS",
    "KEYDETS",
    "SPIDERS",
    "DIPLOMATS",
    "MOCS",
    "BIG GREEN",
    "GREAT DANES",
    "RETRIEVERS",
    "BLUE HOSE",
    "CAMELS",
    "FIGHTING HAWKS",
    "COYOTES",
    "LEATHERNECKS",
    "SALUKIS",
    "REDBIRDS",
    "BLUEJAYS",
    "THUNDERBIRDS",
    "MASTODONS",
    "NORSE",
    "SKYHAWKS",
    "GOLDEN BEARS",
    "FIGHTING CAMELS",
}

# Maps school / nickname / Odds API full name → stable code
NCAAF_ALIASES: dict[str, str] = {
    # SEC
    "ALA": "ALA",
    "ALABAMA": "ALA",
    "ALABAMA CRIMSON TIDE": "ALA",
    "UGA": "UGA",
    "GEORGIA": "UGA",
    "GEORGIA BULLDOGS": "UGA",
    "LSU": "LSU",
    "LOUISIANA STATE": "LSU",
    "LSU TIGERS": "LSU",
    "AUB": "AUB",
    "AUBURN": "AUB",
    "AUBURN TIGERS": "AUB",
    "FLA": "FLA",
    "FLORIDA": "FLA",
    "FLORIDA GATORS": "FLA",
    "TENN": "TENN",
    "TENNESSEE": "TENN",
    "TENNESSEE VOLUNTEERS": "TENN",
    "TEX": "TEX",
    "TEXAS": "TEX",
    "TEXAS LONGHORNS": "TEX",
    "OU": "OU",
    "OKLAHOMA": "OU",
    "OKLAHOMA SOONERS": "OU",
    "TA&M": "TAMU",
    "TAMU": "TAMU",
    "TEXAS A&M": "TAMU",
    "TEXAS A&M AGGIES": "TAMU",
    "ARK": "ARK",
    "ARKANSAS": "ARK",
    "ARKANSAS RAZORBACKS": "ARK",
    "MISS": "MISS",
    "OLE MISS": "MISS",
    "MISSISSIPPI": "MISS",
    "OLE MISS REBELS": "MISS",
    "MSST": "MSST",
    "MISSISSIPPI STATE": "MSST",
    "MISSISSIPPI STATE BULLDOGS": "MSST",
    "MIZZ": "MIZZ",
    "MISSOURI": "MIZZ",
    "MISSOURI TIGERS": "MIZZ",
    "UK": "UK",
    "KENTUCKY": "UK",
    "KENTUCKY WILDCATS": "UK",
    "SCAR": "SCAR",
    "SOUTH CAROLINA": "SCAR",
    "SOUTH CAROLINA GAMECOCKS": "SCAR",
    "VAN": "VAN",
    "VANDERBILT": "VAN",
    "VANDERBILT COMMODORES": "VAN",
    # Big Ten
    "OSU": "OSU",
    "OHIO STATE": "OSU",
    "OHIO ST": "OSU",
    "OHIO STATE BUCKEYES": "OSU",
    "MICH": "MICH",
    "MICHIGAN": "MICH",
    "MICHIGAN WOLVERINES": "MICH",
    "PSU": "PSU",
    "PENN STATE": "PSU",
    "PENN ST": "PSU",
    "PENN STATE NITTANY LIONS": "PSU",
    "ORE": "ORE",
    "OREGON": "ORE",
    "OREGON DUCKS": "ORE",
    "USC": "USC",
    "SOUTHERN CAL": "USC",
    "SOUTHERN CALIFORNIA": "USC",
    "USC TROJANS": "USC",
    "WASH": "WASH",
    "WASHINGTON": "WASH",
    "WASHINGTON HUSKIES": "WASH",
    "UCLA": "UCLA",
    "UCLA BRUINS": "UCLA",
    "WISC": "WISC",
    "WISCONSIN": "WISC",
    "WISCONSIN BADGERS": "WISC",
    "IOWA": "IOWA",
    "IOWA HAWKEYES": "IOWA",
    "MINN": "MINN",
    "MINNESOTA": "MINN",
    "MINNESOTA GOLDEN GOPHERS": "MINN",
    "NEB": "NEB",
    "NEBRASKA": "NEB",
    "NEBRASKA CORNHUSKERS": "NEB",
    "ILL": "ILL",
    "ILLINOIS": "ILL",
    "ILLINOIS FIGHTING ILLINI": "ILL",
    "NW": "NW",
    "NORTHWESTERN": "NW",
    "NORTHWESTERN WILDCATS": "NW",
    "MSU": "MSU",
    "MICHIGAN STATE": "MSU",
    "MICHIGAN ST": "MSU",
    "MICHIGAN STATE SPARTANS": "MSU",
    "IND": "IND",
    "INDIANA": "IND",
    "INDIANA HOOSIERS": "IND",
    "PUR": "PUR",
    "PURDUE": "PUR",
    "PURDUE BOILERMAKERS": "PUR",
    "MD": "MD",
    "MARYLAND": "MD",
    "MARYLAND TERRAPINS": "MD",
    "RUT": "RUT",
    "RUTGERS": "RUT",
    "RUTGERS SCARLET KNIGHTS": "RUT",
    # ACC
    "CLEM": "CLEM",
    "CLEMSON": "CLEM",
    "CLEMSON TIGERS": "CLEM",
    "FSU": "FSU",
    "FLORIDA STATE": "FSU",
    "FLORIDA ST": "FSU",
    "FLORIDA STATE SEMINOLES": "FSU",
    "MIA": "MIA",
    "MIAMI": "MIA",
    "MIAMI FL": "MIA",
    "MIAMI HURRICANES": "MIA",
    "UNC": "UNC",
    "NORTH CAROLINA": "UNC",
    "NORTH CAROLINA TAR HEELS": "UNC",
    "NCST": "NCST",
    "NCSU": "NCST",
    "NC STATE": "NCST",
    "NORTH CAROLINA STATE": "NCST",
    "NC STATE WOLFPACK": "NCST",
    "DUKE": "DUKE",
    "DUKE BLUE DEVILS": "DUKE",
    "VT": "VT",
    "VIRGINIA TECH": "VT",
    "VIRGINIA TECH HOKIES": "VT",
    "UVA": "UVA",
    "VIRGINIA": "UVA",
    "VIRGINIA CAVALIERS": "UVA",
    "GT": "GT",
    "GEORGIA TECH": "GT",
    "GEORGIA TECH YELLOW JACKETS": "GT",
    "LOU": "LOU",
    "LOUISVILLE": "LOU",
    "LOUISVILLE CARDINALS": "LOU",
    "PITT": "PITT",
    "PITTSBURGH": "PITT",
    "PITTSBURGH PANTHERS": "PITT",
    "SYR": "SYR",
    "SYRACUSE": "SYR",
    "SYRACUSE ORANGE": "SYR",
    "BC": "BC",
    "BOSTON COLLEGE": "BC",
    "BOSTON COLLEGE EAGLES": "BC",
    "WAKE": "WAKE",
    "WAKE FOREST": "WAKE",
    "WAKE FOREST DEMON DEACONS": "WAKE",
    "SMU": "SMU",
    "SMU MUSTANGS": "SMU",
    "CAL": "CAL",
    "CALIFORNIA": "CAL",
    "CALIFORNIA GOLDEN BEARS": "CAL",
    "STAN": "STAN",
    "STANFORD": "STAN",
    "STANFORD CARDINAL": "STAN",
    # Big 12
    "BAY": "BAY",
    "BAYLOR": "BAY",
    "BAYLOR BEARS": "BAY",
    "TCU": "TCU",
    "TCU HORNED FROGS": "TCU",
    "KSU": "KSU",
    "KANSAS STATE": "KSU",
    "KANSAS ST": "KSU",
    "KANSAS STATE WILDCATS": "KSU",
    "KU": "KU",
    "KANSAS": "KU",
    "KANSAS JAYHAWKS": "KU",
    "ISU": "ISU",
    "IOWA STATE": "ISU",
    "IOWA ST": "ISU",
    "IOWA STATE CYCLONES": "ISU",
    "TTU": "TTU",
    "TEXAS TECH": "TTU",
    "TEXAS TECH RED RAIDERS": "TTU",
    "OKST": "OKST",
    "OKLAHOMA STATE": "OKST",
    "OKLAHOMA ST": "OKST",
    "OKLAHOMA STATE COWBOYS": "OKST",
    "WVU": "WVU",
    "WEST VIRGINIA": "WVU",
    "WEST VIRGINIA MOUNTAINEERS": "WVU",
    "CIN": "CIN",
    "CINCINNATI": "CIN",
    "CINCINNATI BEARCATS": "CIN",
    "UCF": "UCF",
    "UCF KNIGHTS": "UCF",
    "HOU": "HOU",
    "HOUSTON": "HOU",
    "HOUSTON COUGARS": "HOU",
    "BYU": "BYU",
    "BYU COUGARS": "BYU",
    "ASU": "ASU",
    "ARIZONA STATE": "ASU",
    "ARIZONA ST": "ASU",
    "ARIZONA STATE SUN DEVILS": "ASU",
    "ARIZ": "ARIZ",
    "ARIZONA": "ARIZ",
    "ARIZONA WILDCATS": "ARIZ",
    "COLO": "COLO",
    "COLORADO": "COLO",
    "COLORADO BUFFALOES": "COLO",
    "UTAH": "UTAH",
    "UTAH UTES": "UTAH",
    # Independents / others
    "ND": "ND",
    "NOTRE DAME": "ND",
    "NOTRE DAME FIGHTING IRISH": "ND",
    "ARMY": "ARMY",
    "ARMY BLACK KNIGHTS": "ARMY",
    "NAVY": "NAVY",
    "NAVY MIDSHIPMEN": "NAVY",
    "AF": "AF",
    "AIR FORCE": "AF",
    "AIR FORCE FALCONS": "AF",
    "BSU": "BSU",
    "BOISE STATE": "BSU",
    "BOISE ST": "BSU",
    "BOISE STATE BRONCOS": "BSU",
    "MEM": "MEM",
    "MEMPHIS": "MEM",
    "MEMPHIS TIGERS": "MEM",
    "TULN": "TULN",
    "TULANE": "TULN",
    "TULANE GREEN WAVE": "TULN",
    "USF": "USF",
    "SOUTH FLORIDA": "USF",
    "USF BULLS": "USF",
    "JMU": "JMU",
    "JAMES MADISON": "JMU",
    "JAMES MADISON DUKES": "JMU",
    "LIB": "LIB",
    "LIBERTY": "LIB",
    "LIBERTY FLAMES": "LIB",
    "SDSU": "SDSU",
    "SAN DIEGO STATE": "SDSU",
    "SAN DIEGO STATE AZTECS": "SDSU",
    "FRES": "FRES",
    "FRESNO STATE": "FRES",
    "FRESNO ST": "FRES",
    "FRESNO STATE BULLDOGS": "FRES",
    "UNLV": "UNLV",
    "UNLV REBELS": "UNLV",
    "ORST": "ORST",
    "OREGON STATE": "ORST",
    "OREGON ST": "ORST",
    "OREGON STATE BEAVERS": "ORST",
    "WSU": "WSU",
    "WASHINGTON STATE": "WSU",
    "WASHINGTON ST": "WSU",
    "WASHINGTON STATE COUGARS": "WSU",
    # G5 / MAC — Action Network abbrs vs Odds API school names
    "SJSU": "SAN JOSE STATE",
    "SAN JOSE ST": "SAN JOSE STATE",
    "SAN JOSE STATE": "SAN JOSE STATE",
    "SAN JOSE STATE SPARTANS": "SAN JOSE STATE",
    "JVST": "JACKSONVILLE STATE",
    "JACKSONVILLE ST": "JACKSONVILLE STATE",
    "JACKSONVILLE STATE": "JACKSONVILLE STATE",
    "JACKSONVILLE STATE GAMECOCKS": "JACKSONVILLE STATE",
    "NDSU": "NORTH DAKOTA STATE",
    "NORTH DAKOTA ST": "NORTH DAKOTA STATE",
    "NORTH DAKOTA STATE": "NORTH DAKOTA STATE",
    "NORTH DAKOTA STATE BISON": "NORTH DAKOTA STATE",
    "SAC": "SACRAMENTO STATE",
    "SACRAMENTO ST": "SACRAMENTO STATE",
    "SACRAMENTO STATE": "SACRAMENTO STATE",
    "SACRAMENTO STATE HORNETS": "SACRAMENTO STATE",
    "NMSU": "NEW MEXICO STATE",
    "NEW MEXICO ST": "NEW MEXICO STATE",
    "NEW MEXICO STATE": "NEW MEXICO STATE",
    "NEW MEXICO STATE AGGIES": "NEW MEXICO STATE",
    "HAW": "HAWAII",
    "HAWAII": "HAWAII",
    "HAWAII RAINBOW WARRIORS": "HAWAII",
    "EMU": "EASTERN MICHIGAN",
    "EASTERN MICH": "EASTERN MICHIGAN",
    "EASTERN MICHIGAN": "EASTERN MICHIGAN",
    "EASTERN MICHIGAN EAGLES": "EASTERN MICHIGAN",
    # Remaining FBS: short codes must land on the same canon as the full school name.
    "NIU": "NORTHERN ILLINOIS",
    "NORTHERN ILL": "NORTHERN ILLINOIS",
    "NORTHERN ILLINOIS": "NORTHERN ILLINOIS",
    "APP": "APPALACHIAN STATE",
    "APP STATE": "APPALACHIAN STATE",
    "APP ST": "APPALACHIAN STATE",
    "APPALACHIAN ST": "APPALACHIAN STATE",
    "APPALACHIAN STATE": "APPALACHIAN STATE",
    "USM": "SOUTHERN MISS",
    "SOUTHERN MISS": "SOUTHERN MISS",
    "SOUTHERN MISSISSIPPI": "SOUTHERN MISS",
    "M-OH": "MIAMI OHIO",
    "MIA (OH)": "MIAMI OHIO",
    "MIAMI (OH)": "MIAMI OHIO",
    "MIAMI OH": "MIAMI OHIO",
    "MIAMI OHIO": "MIAMI OHIO",
    "ECU": "EAST CAROLINA",
    "EAST CAROLINA": "EAST CAROLINA",
    "MRSH": "MARSHALL",
    "MARSHALL": "MARSHALL",
    "TULN": "TULANE",
    "TULANE": "TULANE",
    "TLSA": "TULSA",
    "TULSA": "TULSA",
    "TEM": "TEMPLE",
    "TEMPLE": "TEMPLE",
    "AKR": "AKRON",
    "AKRON": "AKRON",
    "KENT": "KENT STATE",
    "KENT ST": "KENT STATE",
    "KENT STATE": "KENT STATE",
    "BGSU": "BOWLING GREEN",
    "BOWLING GREEN": "BOWLING GREEN",
    "CMU": "CENTRAL MICHIGAN",
    "CENTRAL MICH": "CENTRAL MICHIGAN",
    "CENTRAL MICHIGAN": "CENTRAL MICHIGAN",
    "WMU": "WESTERN MICHIGAN",
    "WESTERN MICH": "WESTERN MICHIGAN",
    "WESTERN MICHIGAN": "WESTERN MICHIGAN",
    "TOL": "TOLEDO",
    "TOLEDO": "TOLEDO",
    "BALL": "BALL STATE",
    "BALL ST": "BALL STATE",
    "BALL STATE": "BALL STATE",
    "BUFF": "BUFFALO",
    "BUFFALO": "BUFFALO",
    "OHIO": "OHIO",
    "UMASS": "MASSACHUSETTS",
    "MASSACHUSETTS": "MASSACHUSETTS",
    "UCONN": "CONNECTICUT",
    "CONNECTICUT": "CONNECTICUT",
    "ARMY": "ARMY",
    "NAVY": "NAVY",
    "AF": "AIR FORCE",
    "AIR FORCE": "AIR FORCE",
    "UNT": "NORTH TEXAS",
    "NORTH TEXAS": "NORTH TEXAS",
    "RICE": "RICE",
    "UTEP": "UTEP",
    "UTSA": "UTSA",
    "FAU": "FLORIDA ATLANTIC",
    "FLORIDA ATLANTIC": "FLORIDA ATLANTIC",
    "FIU": "FLORIDA INTERNATIONAL",
    "FLORIDA INTERNATIONAL": "FLORIDA INTERNATIONAL",
    "USF": "USF",
    "SOUTH FLORIDA": "USF",
    "UAB": "UAB",
    "MTSU": "MIDDLE TENNESSEE",
    "MIDDLE TENN": "MIDDLE TENNESSEE",
    "MIDDLE TENNESSEE": "MIDDLE TENNESSEE",
    "WKU": "WESTERN KENTUCKY",
    "WESTERN KENTUCKY": "WESTERN KENTUCKY",
    "LT": "LOUISIANA TECH",
    "LA TECH": "LOUISIANA TECH",
    "LOUISIANA TECH": "LOUISIANA TECH",
    "CHAR": "CHARLOTTE",
    "CHARLOTTE": "CHARLOTTE",
    "ODU": "OLD DOMINION",
    "OLD DOMINION": "OLD DOMINION",
    "GASO": "GEORGIA SOUTHERN",
    "GEORGIA SOUTHERN": "GEORGIA SOUTHERN",
    "GAST": "GEORGIA STATE",
    "GEORGIA STATE": "GEORGIA STATE",
    "TROY": "TROY",
    "USA": "SOUTH ALABAMA",
    "SOUTH ALABAMA": "SOUTH ALABAMA",
    "ARST": "ARKANSAS STATE",
    "ARKANSAS ST": "ARKANSAS STATE",
    "ARKANSAS STATE": "ARKANSAS STATE",
    "TXST": "TEXAS STATE",
    "TEXAS ST": "TEXAS STATE",
    "TEXAS STATE": "TEXAS STATE",
    "ULL": "LOUISIANA",
    "UL LAFAYETTE": "LOUISIANA",
    "LOUISIANA": "LOUISIANA",
    "ULM": "UL MONROE",
    "LOUISIANA MONROE": "UL MONROE",
    "UL MONROE": "UL MONROE",
    "JMU": "JAMES MADISON",
    "JAMES MADISON": "JAMES MADISON",
    "CCU": "COASTAL CAROLINA",
    "COASTAL CAROLINA": "COASTAL CAROLINA",
    "USU": "UTAH STATE",
    "UTAH ST": "UTAH STATE",
    "UTAH STATE": "UTAH STATE",
    "CSU": "COLORADO STATE",
    "COLORADO ST": "COLORADO STATE",
    "COLORADO STATE": "COLORADO STATE",
    "UNM": "NEW MEXICO",
    "NEW MEXICO": "NEW MEXICO",
    "UNLV": "UNLV",
    "NEV": "NEVADA",
    "NEVADA": "NEVADA",
    "FRES": "FRESNO STATE",
    "FRESNO ST": "FRESNO STATE",
    "FRESNO STATE": "FRESNO STATE",
    "WYO": "WYOMING",
    "WYOMING": "WYOMING",
    "IDHO": "IDAHO",
    "IDAHO": "IDAHO",
    "DEL": "DELAWARE",
    "DELAWARE": "DELAWARE",
    "KENN": "KENNESAW STATE",
    "KENNESAW ST": "KENNESAW STATE",
    "KENNESAW STATE": "KENNESAW STATE",
    "MRMK": "MERRIMACK",
    "MERRIMACK": "MERRIMACK",
    # Ampersand schools: matching flattens "&" to " AND ", so pin a clean display canon.
    "NC A&T": "NC A&T",
    "NC A AND T": "NC A&T",
    "NORTH CAROLINA A&T": "NC A&T",
    "NORTH CAROLINA A AND T": "NC A&T",
    "TEXAS A AND M": "TAMU",
    "FLORIDA A&M": "FAMU",
    "FLORIDA A AND M": "FAMU",
    "ALABAMA A&M": "ALABAMA A&M",
    "ALABAMA A AND M": "ALABAMA A&M",
    "PRAIRIE VIEW A&M": "PRAIRIE VIEW A&M",
    "PRAIRIE VIEW A AND M": "PRAIRIE VIEW A&M",
    # Schools the two feeds simply name differently.
    "SAM HOUSTON": "SAM HOUSTON",
    "SAM HOUSTON STATE": "SAM HOUSTON",
    "HOUSTON CHRISTIAN": "HOUSTON CHRISTIAN",
    "HOUSTON BAPTIST": "HOUSTON CHRISTIAN",  # renamed in 2022; Odds API still uses the old name
    "UNIVERSITY AT ALBANY": "ALBANY",
    "UALBANY": "ALBANY",
    "ALBANY": "ALBANY",
    "ALB": "ALBANY",
    "RUTG": "RUT",
    "MASS": "MASSACHUSETTS",
    "EIU": "EASTERN ILLINOIS",
    "THE CITADEL": "CITADEL",
    "CITADEL": "CITADEL",
    "YOUNGSTOWN STATE": "YOUNGSTOWN STATE",
}

NCAAF_DEMO_TEAMS = [
    "ALA", "UGA", "OSU", "MICH", "TEX", "OU", "ORE", "PSU",
    "CLEM", "ND", "LSU", "FSU", "MIA", "USC", "UCLA", "WASH",
    "TENN", "TAMU", "FLA", "AUB",
]


def _strip_mascot(name: str) -> str:
    up = re.sub(r"\s+", " ", name.strip().upper())
    # Longest mascot first
    for mascot in sorted(_MASCOTS, key=len, reverse=True):
        if up.endswith(" " + mascot):
            return up[: -len(mascot) - 1].strip()
    return up


# Mascots learned at runtime from the Action Network payload's ``short_name`` field.
# The feed tells us every mascot, which beats hand-maintaining a list that silently
# rots. Never trim a *school* qualifier here: "Arkansas-Pine Bluff" must not collapse
# to "Arkansas", so only known mascots are ever removed.
_LEARNED_MASCOTS: set[str] = set()


def register_mascots(names: Iterable[str]) -> None:
    for name in names:
        cleaned = re.sub(r"\s+", " ", _simplify_punct(name or "")).strip()
        if len(cleaned) > 2:
            _LEARNED_MASCOTS.add(cleaned)


def _simplify_punct(name: str) -> str:
    """Upper-case and flatten punctuation so "Arkansas-Pine Bluff" == "ARKANSAS PINE BLUFF"."""
    up = (name or "").upper().replace("&", " AND ")
    up = re.sub(r"[.'`’]", "", up)
    up = re.sub(r"[-/(),]", " ", up)
    up = re.sub(r"\s+", " ", up).strip()
    # Feeds mix "Youngstown St" and "Youngstown State"; treat the suffix as one token.
    up = re.sub(r"\bST$", "STATE", up)
    return re.sub(r"^(THE|UNIVERSITY AT|UNIV AT) ", "", up)


def normalize_ncaaf(name: str) -> str:
    raw = re.sub(r"\s+", " ", (name or "").strip().upper())
    if not raw or raw == "NAN":
        return raw
    if raw in NCAAF_ALIASES:
        return NCAAF_ALIASES[raw]
    stripped = _strip_mascot(raw)
    if stripped in NCAAF_ALIASES:
        return NCAAF_ALIASES[stripped]

    # Punctuation-insensitive retry, then remove a mascot the feed taught us.
    flat = _simplify_punct(raw)
    if flat in NCAAF_ALIASES:
        return NCAAF_ALIASES[flat]
    # Re-simplify after mascot removal so suffix rules ("ST" → "STATE") still apply.
    flat_stripped = _simplify_punct(_strip_mascot(flat))
    if flat_stripped in NCAAF_ALIASES:
        return NCAAF_ALIASES[flat_stripped]
    for mascot in sorted(_LEARNED_MASCOTS, key=len, reverse=True):
        if flat.endswith(" " + mascot):
            school = _simplify_punct(flat[: -len(mascot) - 1])
            return NCAAF_ALIASES.get(school, school)
    if flat_stripped != raw:
        return flat_stripped
    if stripped in NCAAF_ALIASES:
        return NCAAF_ALIASES[stripped]
    # Already a short code
    if raw in NCAAF_ALIASES.values():
        return raw
    return stripped or raw


_DISPLAY_CODES: dict[str, str] | None = None


def _preferred_display_codes() -> dict[str, str]:
    """Canonical school name → short label for dense UI tables."""
    best: dict[str, tuple[tuple[int, int], str]] = {}
    for key, canon in NCAAF_ALIASES.items():
        if " " in key or len(key) > 8:
            continue
        # Prefer familiar abbreviations (NDSU, SJSU) over longer or punctuated codes.
        score = (0 if key.isalnum() else 1, 0 if len(key) <= 5 else 1, len(key))
        prev = best.get(canon)
        if prev is None or score < prev[0]:
            best[canon] = (score, key)
    return {canon: key for canon, (_, key) in best.items()}


def ncaaf_display_code(name: str) -> str:
    """Short board label for NCAAF teams (e.g. NORTH DAKOTA STATE → NDSU)."""
    global _DISPLAY_CODES
    if _DISPLAY_CODES is None:
        _DISPLAY_CODES = _preferred_display_codes()
    canon = normalize_ncaaf(name)
    if not canon:
        return name or ""
    if canon in _DISPLAY_CODES:
        return _DISPLAY_CODES[canon]
    if len(canon) <= 8:
        # Already board-sized ("NC A&T"); initials would only obscure it.
        return canon
    parts = [p for p in canon.split() if p not in {"STATE", "ST", "UNIVERSITY", "OF"}]
    if len(parts) == 1:
        return parts[0][:8]
    return "".join(p[0] for p in parts)[:6]
