"""NCAA football team normalization (FBS + common Odds API / cfbfastR names)."""

from __future__ import annotations

import re

# Common mascots stripped so "Alabama Crimson Tide" → "ALABAMA"
_MASCOTS = {
    "CRIMSON TIDE",
    "BULLDOGS",
    "TIGERS",
    "WILDCATS",
    "BEARS",
    "EAGLES",
    "HAWKS",
    "LIONS",
    "PANTHERS",
    "COUGARS",
    "HUSKIES",
    "SPARTANS",
    "WOLVERINES",
    "BUCKEYES",
    "SOONERS",
    "LONGHORNS",
    "NITTANY LIONS",
    "FIGHTING IRISH",
    "TROJANS",
    "BRUINS",
    "DUCKS",
    "BEAVERS",
    "HURRICANES",
    "SEMINOLES",
    "GATORS",
    "VOLUNTEERS",
    "COMMODORES",
    "GAMECOCKS",
    "TAR HEELS",
    "BLUE DEVILS",
    "ORANGE",
    "HOOSIERS",
    "BOILERMAKERS",
    "BADGERS",
    "HAWKEYES",
    "GOLDEN GOPHERS",
    "CORNHUSKERS",
    "TERRAPINS",
    "SCARLET KNIGHTS",
    "MOUNTAINEERS",
    "RAZORBACKS",
    "AGGIES",
    "REBELS",
    "GREEN WAVE",
    "MEAN GREEN",
    "HORNED FROGS",
    "MUSTANGS",
    "BEARCATS",
    "BEAR CATS",
    "CARDINALS",
    "SUN DEVILS",
    "UTES",
    "BUFFALOES",
    "COWBOYS",
    "CYCLONES",
    "JAYHAWKS",
    "RED RAIDERS",
    "HOOSIERS",
    "BOILERMAKERS",
    "FIGHTING ILLINI",
    "WILDCATS",
    "HOKIES",
    "CAVALIERS",
    "YELLOW JACKETS",
    "DEMON DEACONS",
    "WOLFPACK",
    "BLUE RAIDERS",
    "THUNDERING HERD",
    "GOLDEN EAGLES",
    "ROCKETS",
    "FALCONS",
    "BOBCATS",
    "CHIPPEWAS",
    "BRONCOS",
    "ROCKY MOUNTAIN",
    "RAINBOW WARRIORS",
    "WARRIORS",
    "HORNETS",
    "BISON",
    "GAMECOCKS",
    "AZTECS",
    "WOLFPACK",
    "FROGS",
    "SOONERS",
}

# Maps school / nickname / Odds API full name → stable code
NCAAF_ALIASES: dict[str, str] = {
    # SEC
    "ALA": "ALA",
    "ALABAMA": "ALA",
    "ALABAMA CRIMSON TIDE": "ALA",
    "UGA": "UGA",
    "GEORGIA": "UGA",
    "GEORGIA BULLDOGS": "UGA",
    "LSU": "LSU",
    "LOUISIANA STATE": "LSU",
    "LSU TIGERS": "LSU",
    "AUB": "AUB",
    "AUBURN": "AUB",
    "AUBURN TIGERS": "AUB",
    "FLA": "FLA",
    "FLORIDA": "FLA",
    "FLORIDA GATORS": "FLA",
    "TENN": "TENN",
    "TENNESSEE": "TENN",
    "TENNESSEE VOLUNTEERS": "TENN",
    "TEX": "TEX",
    "TEXAS": "TEX",
    "TEXAS LONGHORNS": "TEX",
    "OU": "OU",
    "OKLAHOMA": "OU",
    "OKLAHOMA SOONERS": "OU",
    "TA&M": "TAMU",
    "TAMU": "TAMU",
    "TEXAS A&M": "TAMU",
    "TEXAS A&M AGGIES": "TAMU",
    "ARK": "ARK",
    "ARKANSAS": "ARK",
    "ARKANSAS RAZORBACKS": "ARK",
    "MISS": "MISS",
    "OLE MISS": "MISS",
    "MISSISSIPPI": "MISS",
    "OLE MISS REBELS": "MISS",
    "MSST": "MSST",
    "MISSISSIPPI STATE": "MSST",
    "MISSISSIPPI STATE BULLDOGS": "MSST",
    "MIZZ": "MIZZ",
    "MISSOURI": "MIZZ",
    "MISSOURI TIGERS": "MIZZ",
    "UK": "UK",
    "KENTUCKY": "UK",
    "KENTUCKY WILDCATS": "UK",
    "SCAR": "SCAR",
    "SOUTH CAROLINA": "SCAR",
    "SOUTH CAROLINA GAMECOCKS": "SCAR",
    "VAN": "VAN",
    "VANDERBILT": "VAN",
    "VANDERBILT COMMODORES": "VAN",
    # Big Ten
    "OSU": "OSU",
    "OHIO STATE": "OSU",
    "OHIO ST": "OSU",
    "OHIO STATE BUCKEYES": "OSU",
    "MICH": "MICH",
    "MICHIGAN": "MICH",
    "MICHIGAN WOLVERINES": "MICH",
    "PSU": "PSU",
    "PENN STATE": "PSU",
    "PENN ST": "PSU",
    "PENN STATE NITTANY LIONS": "PSU",
    "ORE": "ORE",
    "OREGON": "ORE",
    "OREGON DUCKS": "ORE",
    "USC": "USC",
    "SOUTHERN CAL": "USC",
    "SOUTHERN CALIFORNIA": "USC",
    "USC TROJANS": "USC",
    "WASH": "WASH",
    "WASHINGTON": "WASH",
    "WASHINGTON HUSKIES": "WASH",
    "UCLA": "UCLA",
    "UCLA BRUINS": "UCLA",
    "WISC": "WISC",
    "WISCONSIN": "WISC",
    "WISCONSIN BADGERS": "WISC",
    "IOWA": "IOWA",
    "IOWA HAWKEYES": "IOWA",
    "MINN": "MINN",
    "MINNESOTA": "MINN",
    "MINNESOTA GOLDEN GOPHERS": "MINN",
    "NEB": "NEB",
    "NEBRASKA": "NEB",
    "NEBRASKA CORNHUSKERS": "NEB",
    "ILL": "ILL",
    "ILLINOIS": "ILL",
    "ILLINOIS FIGHTING ILLINI": "ILL",
    "NW": "NW",
    "NORTHWESTERN": "NW",
    "NORTHWESTERN WILDCATS": "NW",
    "MSU": "MSU",
    "MICHIGAN STATE": "MSU",
    "MICHIGAN ST": "MSU",
    "MICHIGAN STATE SPARTANS": "MSU",
    "IND": "IND",
    "INDIANA": "IND",
    "INDIANA HOOSIERS": "IND",
    "PUR": "PUR",
    "PURDUE": "PUR",
    "PURDUE BOILERMAKERS": "PUR",
    "MD": "MD",
    "MARYLAND": "MD",
    "MARYLAND TERRAPINS": "MD",
    "RUT": "RUT",
    "RUTGERS": "RUT",
    "RUTGERS SCARLET KNIGHTS": "RUT",
    # ACC
    "CLEM": "CLEM",
    "CLEMSON": "CLEM",
    "CLEMSON TIGERS": "CLEM",
    "FSU": "FSU",
    "FLORIDA STATE": "FSU",
    "FLORIDA ST": "FSU",
    "FLORIDA STATE SEMINOLES": "FSU",
    "MIA": "MIA",
    "MIAMI": "MIA",
    "MIAMI FL": "MIA",
    "MIAMI HURRICANES": "MIA",
    "UNC": "UNC",
    "NORTH CAROLINA": "UNC",
    "NORTH CAROLINA TAR HEELS": "UNC",
    "NCST": "NCST",
    "NC STATE": "NCST",
    "NORTH CAROLINA STATE": "NCST",
    "NC STATE WOLFPACK": "NCST",
    "DUKE": "DUKE",
    "DUKE BLUE DEVILS": "DUKE",
    "VT": "VT",
    "VIRGINIA TECH": "VT",
    "VIRGINIA TECH HOKIES": "VT",
    "UVA": "UVA",
    "VIRGINIA": "UVA",
    "VIRGINIA CAVALIERS": "UVA",
    "GT": "GT",
    "GEORGIA TECH": "GT",
    "GEORGIA TECH YELLOW JACKETS": "GT",
    "LOU": "LOU",
    "LOUISVILLE": "LOU",
    "LOUISVILLE CARDINALS": "LOU",
    "PITT": "PITT",
    "PITTSBURGH": "PITT",
    "PITTSBURGH PANTHERS": "PITT",
    "SYR": "SYR",
    "SYRACUSE": "SYR",
    "SYRACUSE ORANGE": "SYR",
    "BC": "BC",
    "BOSTON COLLEGE": "BC",
    "BOSTON COLLEGE EAGLES": "BC",
    "WAKE": "WAKE",
    "WAKE FOREST": "WAKE",
    "WAKE FOREST DEMON DEACONS": "WAKE",
    "SMU": "SMU",
    "SMU MUSTANGS": "SMU",
    "CAL": "CAL",
    "CALIFORNIA": "CAL",
    "CALIFORNIA GOLDEN BEARS": "CAL",
    "STAN": "STAN",
    "STANFORD": "STAN",
    "STANFORD CARDINAL": "STAN",
    # Big 12
    "BAY": "BAY",
    "BAYLOR": "BAY",
    "BAYLOR BEARS": "BAY",
    "TCU": "TCU",
    "TCU HORNED FROGS": "TCU",
    "KSU": "KSU",
    "KANSAS STATE": "KSU",
    "KANSAS ST": "KSU",
    "KANSAS STATE WILDCATS": "KSU",
    "KU": "KU",
    "KANSAS": "KU",
    "KANSAS JAYHAWKS": "KU",
    "ISU": "ISU",
    "IOWA STATE": "ISU",
    "IOWA ST": "ISU",
    "IOWA STATE CYCLONES": "ISU",
    "TTU": "TTU",
    "TEXAS TECH": "TTU",
    "TEXAS TECH RED RAIDERS": "TTU",
    "OKST": "OKST",
    "OKLAHOMA STATE": "OKST",
    "OKLAHOMA ST": "OKST",
    "OKLAHOMA STATE COWBOYS": "OKST",
    "WVU": "WVU",
    "WEST VIRGINIA": "WVU",
    "WEST VIRGINIA MOUNTAINEERS": "WVU",
    "CIN": "CIN",
    "CINCINNATI": "CIN",
    "CINCINNATI BEARCATS": "CIN",
    "UCF": "UCF",
    "UCF KNIGHTS": "UCF",
    "HOU": "HOU",
    "HOUSTON": "HOU",
    "HOUSTON COUGARS": "HOU",
    "BYU": "BYU",
    "BYU COUGARS": "BYU",
    "ASU": "ASU",
    "ARIZONA STATE": "ASU",
    "ARIZONA ST": "ASU",
    "ARIZONA STATE SUN DEVILS": "ASU",
    "ARIZ": "ARIZ",
    "ARIZONA": "ARIZ",
    "ARIZONA WILDCATS": "ARIZ",
    "COLO": "COLO",
    "COLORADO": "COLO",
    "COLORADO BUFFALOES": "COLO",
    "UTAH": "UTAH",
    "UTAH UTES": "UTAH",
    # Independents / others
    "ND": "ND",
    "NOTRE DAME": "ND",
    "NOTRE DAME FIGHTING IRISH": "ND",
    "ARMY": "ARMY",
    "ARMY BLACK KNIGHTS": "ARMY",
    "NAVY": "NAVY",
    "NAVY MIDSHIPMEN": "NAVY",
    "AF": "AF",
    "AIR FORCE": "AF",
    "AIR FORCE FALCONS": "AF",
    "BSU": "BSU",
    "BOISE STATE": "BSU",
    "BOISE ST": "BSU",
    "BOISE STATE BRONCOS": "BSU",
    "MEM": "MEM",
    "MEMPHIS": "MEM",
    "MEMPHIS TIGERS": "MEM",
    "TULN": "TULN",
    "TULANE": "TULN",
    "TULANE GREEN WAVE": "TULN",
    "USF": "USF",
    "SOUTH FLORIDA": "USF",
    "USF BULLS": "USF",
    "JMU": "JMU",
    "JAMES MADISON": "JMU",
    "JAMES MADISON DUKES": "JMU",
    "LIB": "LIB",
    "LIBERTY": "LIB",
    "LIBERTY FLAMES": "LIB",
    "SDSU": "SDSU",
    "SAN DIEGO STATE": "SDSU",
    "SAN DIEGO STATE AZTECS": "SDSU",
    "FRES": "FRES",
    "FRESNO STATE": "FRES",
    "FRESNO ST": "FRES",
    "FRESNO STATE BULLDOGS": "FRES",
    "UNLV": "UNLV",
    "UNLV REBELS": "UNLV",
    "ORST": "ORST",
    "OREGON STATE": "ORST",
    "OREGON ST": "ORST",
    "OREGON STATE BEAVERS": "ORST",
    "WSU": "WSU",
    "WASHINGTON STATE": "WSU",
    "WASHINGTON ST": "WSU",
    "WASHINGTON STATE COUGARS": "WSU",
    # G5 / MAC — Action Network abbrs vs Odds API school names
    "SJSU": "SAN JOSE STATE",
    "SAN JOSE ST": "SAN JOSE STATE",
    "SAN JOSE STATE": "SAN JOSE STATE",
    "SAN JOSE STATE SPARTANS": "SAN JOSE STATE",
    "JVST": "JACKSONVILLE STATE",
    "JACKSONVILLE ST": "JACKSONVILLE STATE",
    "JACKSONVILLE STATE": "JACKSONVILLE STATE",
    "JACKSONVILLE STATE GAMECOCKS": "JACKSONVILLE STATE",
    "NDSU": "NORTH DAKOTA STATE",
    "NORTH DAKOTA ST": "NORTH DAKOTA STATE",
    "NORTH DAKOTA STATE": "NORTH DAKOTA STATE",
    "NORTH DAKOTA STATE BISON": "NORTH DAKOTA STATE",
    "SAC": "SACRAMENTO STATE",
    "SACRAMENTO ST": "SACRAMENTO STATE",
    "SACRAMENTO STATE": "SACRAMENTO STATE",
    "SACRAMENTO STATE HORNETS": "SACRAMENTO STATE",
    "NMSU": "NEW MEXICO STATE",
    "NEW MEXICO ST": "NEW MEXICO STATE",
    "NEW MEXICO STATE": "NEW MEXICO STATE",
    "NEW MEXICO STATE AGGIES": "NEW MEXICO STATE",
    "HAW": "HAWAII",
    "HAWAII": "HAWAII",
    "HAWAII RAINBOW WARRIORS": "HAWAII",
    "EMU": "EASTERN MICHIGAN",
    "EASTERN MICH": "EASTERN MICHIGAN",
    "EASTERN MICHIGAN": "EASTERN MICHIGAN",
    "EASTERN MICHIGAN EAGLES": "EASTERN MICHIGAN",
}

NCAAF_DEMO_TEAMS = [
    "ALA", "UGA", "OSU", "MICH", "TEX", "OU", "ORE", "PSU",
    "CLEM", "ND", "LSU", "FSU", "MIA", "USC", "UCLA", "WASH",
    "TENN", "TAMU", "FLA", "AUB",
]


def _strip_mascot(name: str) -> str:
    up = re.sub(r"\s+", " ", name.strip().upper())
    # Longest mascot first
    for mascot in sorted(_MASCOTS, key=len, reverse=True):
        if up.endswith(" " + mascot):
            return up[: -len(mascot) - 1].strip()
    return up


def normalize_ncaaf(name: str) -> str:
    raw = re.sub(r"\s+", " ", (name or "").strip().upper())
    if not raw or raw == "NAN":
        return raw
    if raw in NCAAF_ALIASES:
        return NCAAF_ALIASES[raw]
    stripped = _strip_mascot(raw)
    if stripped in NCAAF_ALIASES:
        return NCAAF_ALIASES[stripped]
    # Already a short code
    if raw in NCAAF_ALIASES.values():
        return raw
    return stripped or raw
